### ISSUE TITLE
yaml FD_control

### ISSUE THREAD

**Issue by ococrook** [Jhsmit/PyHDX#303]
If I don't have a fully deuterated/ back exchange control is there a way to specifcy the yaml so that it ignores this. If I leave it blank the code complains ?

**Comment by Jhsmit** [comment]
You can use a flat percentage for the back exchange as well.
You can do so from yaml writing:

```yaml
  be_percent: 0.
```

instead of a "FD_control" entry.

Which will set the back exchange set zero; and then RFU will be equal to `"uptake"` / `"ex_residues"`

in this function here: https://github.com/Jhsmit/PyHDX/blob/dc82a4aeedcddad1e588c4bf2a6bda25b6c20694/pyhdx/models.py#L349

Sorry, this part isnt so well documented and the API isnt very nice. I'm planning to upgrade it in the future. I'll make an Issue on this at some point then perhaps you can give me some input on how to make it better.

**Comment by ococrook** [comment]
no problem about documentation, it's a little hard seeing where everything is happening but pretty much there now! Happy to help go through the documentation with you so follows from the outsiders perspective
